server:
  port: 8080
spring:
  application:
    name: jiyun-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能