spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///h1910c_dame
    username: root
    password: 123
  application:
    name: jiyun-provider

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka